configProperties:
  version: v2

application:
  name: artifact-hub
  manifestType: helmGit
  resourcePath: ["charts/artifact-hub"]
  helmValues:
    - key: postgresql.persistence.size
      value: 10Gi
    - key: hub.ingress.annotations
      value:
        kubernetes.io/ingress.class: nginx-internal
        alb.ingress.kubernetes.io/scheme: internet-facing
        alb.ingress.kubernetes.io/target-type: ip
        alb.ingress.kubernetes.io/listen-ports: '[{ "HTTP": 80 }]'
  services:
    - name: hub
      serviceType: deployment
      containers:
        - name: hub
          dev:
            gitUrl: https://github.com/jack230230/hub.git
            image: codingcorp-docker.pkg.coding.net/nocalhost/dev-images/golang:latest
            shell: "bash"
            workDir: "/root/nocalhost-dev"
            resources:
              limits:
                cpu: "1"
                memory: 1Gi
              requests:
                cpu: "0.5"
                memory: 512Mi
            persistentVolumeDirs:
              - path: "/root"
                capacity: 10Gi
            sync: 
              type: send
              filePattern: 
                - "."
              ignoreFilePattern:
                - ".git"
